
server.port: 9411

## 使用 mysql 存储
#zipkin.storage.type: mysql
#spring.datasource:
#  url: jdbc:mysql://127.0.0.1:3306/zipkin?useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&queryInterceptors=com.github.common.sql.ShowSql8Interceptor
#  username: root
#  password: root
#  schema: classpath:/mysql.sql
#  initialize: true
#  continue-on-error: true
#  hikari:
#    minimumIdle: 1
#    maximumPoolSize: 1

## 使用 rabbitmq 存储的话
#zipkin.collector:
#  rabbitmq:
#    addresses: ip:port
#    password: guest
#    username: guest
#    queue: zipkin
